// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerURL():Promise<string>;

export function SetServerURL(arg1:string):Promise<void>;
